# Configurações do site — gerado pelo admin
whatsapp_numero: "5548998015006"
instagram_url: "https://www.instagram.com/__dfantato/"
mensagem_whatsapp: "Olá! Tenho interesse na peça *{nome}*. Poderia me passar mais informações?"
alma_whatsapp_numero: "5516997926732"
alma_instagram_url: "https://www.instagram.com/alma_emcontas?igsh=eW81dXMyOHJjaXdh"
cidade: "Ribeirao Bonito/SP"
