whatsapp_numero: "5548988746307"
instagram_url: "https://www.instagram.com/__dfantato/"
cidade: "Tubarão / SC"
mensagem_whatsapp: "Olá! Tenho interesse na peça *{nome}*. Poderia me passar mais informações?"
